### ISSUE TITLE
Add Stack interface and implementation

### ISSUE THREAD

**Issue by constantinosgeorgiou** [constantinosgeorgiou/c-toolbox#45]
### To-do
- [x] Add documentation.
- [x] Add interface file, `stack.h`
- [ ] Add implementation 
- [x] Add tests.

### Interface
- [x] `stack_create()`: Creates a stack.
- [x] `stack_destroy()`: Destroys a stack
- [x] `stack_peek()`: Returns the first element of the stack without removing it.
- [x] `stack_push()`: Adds a new element on top of the stack.
- [x] `stack_pop()`: Removes the top element of the stack.
- [x] `stack_set_destroy_value()`: Sets the destroy value.
- [x] `stack_is_empty()`: Returns true if stack is empty, or false, if not.
- [x] `stack_size()`: Returns the number of elements in the stack.

### Implementation
The stack is gonna be implemented using a Linked List data structure.
- [x] `stack_create()`
- [x] `stack_destroy()`
- [x] `stack_peek()`
- [x] `stack_push()`
- [x] `stack_pop()`
- [x] `stack_set_destroy_value()`
- [x] `stack_is_empty()`
- [x] `stack_size()`
